services:
  - type: web
    name: cars-api
    runtime: node
    plan: free
    buildCommand: npm ci && npm ci --prefix frontend && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
